In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import scipy.stats as ss

In [2]:
gsm = pd.read_csv('../../data_tables/gsm/DLBCL.699.163drivers.Sep_23_2022.tsv', 
                  sep='\t', index_col=1).drop('gene', axis=1)
gsm.head()


DLBCL11470  DLBCL10900  DLBC_FF_A7CQ_TP_NB  DLBCL10462  \
classifier_name                                                           
SV.BCL6                   3           0                   0           3   
DTX1                      2           1                   0           0   
CD70                      2           0                   0           0   
TNFAIP3                   2           0                   0           2   
NOTCH2                    0           0                   0           2   

                 DLBCL_RICOVER_1081  DLBCL_LS1098  DLBCL_RICOVER_299  \
classifier_name                                                        
SV.BCL6                           0             0                  0   
DTX1                              0             0                  0   
CD70                              2             0                  0   
TNFAIP3                           0             0                  0   
NOTCH2                            0             0                  0   

                 DLBCL11558  DLBCL_C_D_1105_NULLPAIR  DLBCL11447  ...  \
classifier_name                                                   ...   
SV.BCL6                   0                        0           0  ...   
DTX1                      0                        2           0  ...   
CD70                      0                        0           0  ...   
TNFAIP3                   0                        0           0  ...   
NOTCH2                    0                        2           0  ...   

                 DLBCL11455  DLBCL_RICOVER_685  DLBCL_LS146  \
classifier_name                                               
SV.BCL6                   0                  0            0   
DTX1                      1                  0            0   
CD70                      0                  0            0   
TNFAIP3                   0                  0            0   
NOTCH2                    0                  0            2   

                 DLBCL_RICOVER_111  DLBCL_RICOVER_173  DLBCL11515  DLBCL10491  \
classifier_name                                                                 
SV.BCL6                          0                  0           0           0   
DTX1                             0                  0           0           0   
CD70                             0                  0           0           0   
TNFAIP3                          0                  0           0           0   
NOTCH2                           0                  0           0           0   

                 DLBCL_RICOVER_1046  DLBCL10547  DLBCL10998  
classifier_name                                              
SV.BCL6                           0           0           0  
DTX1                              0           0           0  
CD70                              0           0           0  
TNFAIP3                           0           2           2  
NOTCH2                            0           0           2  

[5 rows x 699 columns]

In [3]:
for c in gsm.index:
    if 'X9P24' in c:
        print(c)

X9P24.1.AMP


In [4]:
# CD70 vs 19P13.3 mutual
m_cd70 = np.matrix([[0,0], [0,0]])

m_cd70[0, 0] = ((gsm.loc['CD70'] == 2) & (gsm.loc['X19P13.3.DEL'] != 0)).sum()
m_cd70[0, 1] = ((gsm.loc['CD70'] == 2) & (gsm.loc['X19P13.3.DEL'] == 0)).sum()
m_cd70[1, 0] = ((gsm.loc['CD70'] == 0) & (gsm.loc['X19P13.3.DEL'] != 0)).sum()
m_cd70[1, 1] = ((gsm.loc['CD70'] == 0) & (gsm.loc['X19P13.3.DEL'] == 0)).sum()

print('CD70 vs 19P13.3.DEL\np=' + str(ss.fisher_exact(m_cd70, alternative='less')[1]))
m_cd70

CD70 vs 19P13.3.DEL
p=0.03612368079882529


matrix([[  6,  60],
        [116, 515]])

In [6]:
# B2M vs 15Q15.3
m_b2m = np.matrix([[0,0], [0,0]])

m_b2m[0, 0] = ((gsm.loc['B2M'] == 2) & (gsm.loc['X15Q15.3.DEL'] != 0)).sum()
m_b2m[0, 1] = ((gsm.loc['B2M'] == 2) & (gsm.loc['X15Q15.3.DEL'] == 0)).sum()
m_b2m[1, 0] = ((gsm.loc['B2M'] == 0) & (gsm.loc['X15Q15.3.DEL'] != 0)).sum()
m_b2m[1, 1] = ((gsm.loc['B2M'] == 0) & (gsm.loc['X15Q15.3.DEL'] == 0)).sum()

print('B2M vs 15Q15.3.DEL\np=' + str(ss.fisher_exact(m_b2m, alternative='greater')[1]))
m_b2m

B2M vs 15Q15.3.DEL
p=0.002069633506829779


matrix([[ 33,  51],
        [145, 470]])

In [7]:
# HLA (union) vs 6Q21
m_hla = np.matrix([[0,0], [0,0]])
hla_condition = (gsm.loc['HLA.A'] == 2) | (gsm.loc['HLA.B'] == 2) | (gsm.loc['HLA.C'] == 2)

m_hla[0, 0] = (hla_condition & (gsm.loc['X6Q21.DEL'] != 0)).sum()
m_hla[0, 1] = (hla_condition & (gsm.loc['X6Q21.DEL'] == 0)).sum()
m_hla[1, 0] = (~hla_condition & (gsm.loc['X6Q21.DEL'] != 0)).sum()
m_hla[1, 1] = (~hla_condition & (gsm.loc['X6Q21.DEL'] == 0)).sum()

print('HLA (union) vs 6Q21.DEL\np=' + str(ss.fisher_exact(m_hla, alternative='greater')[1]))
m_hla

HLA (union) vs 6Q21.DEL
p=0.2640690302688461


matrix([[ 17, 113],
        [ 61, 508]])

In [8]:
# CD58 vs 1P31.1
m_cd58 = np.matrix([[0,0], [0,0]])

m_cd58[0, 0] = ((gsm.loc['CD58'] == 2) & (gsm.loc['X1P31.1.DEL'] != 0)).sum()
m_cd58[0, 1] = ((gsm.loc['CD58'] == 2) & (gsm.loc['X1P31.1.DEL'] == 0)).sum()
m_cd58[1, 0] = ((gsm.loc['CD58'] == 0) & (gsm.loc['X1P31.1.DEL'] != 0)).sum()
m_cd58[1, 1] = ((gsm.loc['CD58'] == 0) & (gsm.loc['X1P31.1.DEL'] == 0)).sum()

print('CD58 vs 1P31.1.DEL\np=' + str(ss.fisher_exact(m_cd58, alternative='greater')[1]))
m_cd58

CD58 vs 1P31.1.DEL
p=0.4942726073545326


matrix([[  9,  48],
        [ 96, 546]])

In [9]:
# FAS vs 10Q23.31
m_fas = np.matrix([[0,0], [0,0]])

m_fas[0, 0] = ((gsm.loc['FAS'] == 2) & (gsm.loc['X10Q23.31.DEL'] != 0)).sum()
m_fas[0, 1] = ((gsm.loc['FAS'] == 2) & (gsm.loc['X10Q23.31.DEL'] == 0)).sum()
m_fas[1, 0] = ((gsm.loc['FAS'] == 0) & (gsm.loc['X10Q23.31.DEL'] != 0)).sum()
m_fas[1, 1] = ((gsm.loc['FAS'] == 0) & (gsm.loc['X10Q23.31.DEL'] == 0)).sum()

print('FAS vs 10Q23.31.DEL\np=' + str(ss.fisher_exact(m_fas, alternative='greater')[1]))
m_fas

FAS vs 10Q23.31.DEL
p=0.5181171159393316


matrix([[  8,  57],
        [ 75, 559]])

In [10]:
# CD274 vs 9P24.1
m_cd274 = np.matrix([[0,0], [0,0]])

m_cd274[0, 0] = ((gsm.loc['CD274'] == 2) & (gsm.loc['X9P24.1.AMP'] != 0)).sum()
m_cd274[0, 1] = ((gsm.loc['CD274'] == 2) & (gsm.loc['X9P24.1.AMP'] == 0)).sum()
m_cd274[1, 0] = ((gsm.loc['CD274'] == 0) & (gsm.loc['X9P24.1.AMP'] != 0)).sum()
m_cd274[1, 1] = ((gsm.loc['CD274'] == 0) & (gsm.loc['X9P24.1.AMP'] == 0)).sum()

print('FAS vs 9P24.1.AMP\np=' + str(ss.fisher_exact(m_cd274, alternative='greater')[1]))
m_cd274

FAS vs 9P24.1.AMP
p=0.7900351076487336


matrix([[  2,  16],
        [105, 576]])